server:
  port: 8080
#----------------
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://db:5432/employee_management_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

